### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by hmonteiro** [kostapc/putty-tunnel-manager#24]
After resuming from a hibernated state and left-clicking in the task bar icon, the following error was issued:
System.NullReferenceException: Object reference not set to an instance of an object.
   at JoeriBekker.PuttyTunnelManager.Forms.TipForm.UpdateSessions()
   at System.Windows.Forms.Form.OnShown(EventArgs e)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.runTryCode(Object userData)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()

**Comment by kostapc** [comment]
Thanks for your report! I'll try to fix it soon. Any MR are welcome.

**Comment by kostapc** [comment]
please test this build: https://github.com/kostapc/putty-tunnel-manager/blob/feature/auto_reconnect/ptman.exe

i have not environment with hibernation now.

**Comment by kostapc** [comment]
https://github.com/kostapc/Putty-Tunnel-Manager/releases/tag/0.10.4
